Rails:
  Enabled: true

Layout/AlignHash:
  Exclude:
    - 'config/initializers/simple_form.rb'

# Cop supports --auto-correct.
Layout/EmptyLineAfterMagicComment:
  Exclude:
    - 'db/schema.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Layout/ExtraSpacing:
  Exclude:
    - 'bin/setup'
    - 'config.ru'

Metrics/AbcSize:
  Max: 16

Metrics/BlockLength:
  Max: 120

Metrics/MethodLength:
  Max: 11

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 180
  Exclude:
    - 'db/seeds.rb'


