version: "2"
services:
  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sample
      POSTGRES_DB: whalebirdsocial
    volumes:
      - storage:/var/lib/postgres/data

  rails:
    image: ghcr.io/h3poteto/rails-node:3.1.3-node16-slim-bullseye
    environment:
      BUNDLE_APP_CONFIG: /usr/src/app/.bundle
      SERVER_EMAIL: $SERVER_EMAIL
      SERVER_EMAIL_PASSWORD: $SERVER_EMAIL_PASSWORD
      WEB_EMAIL: $WEB_EMAIL
      SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
      RECAPTCHA_SITE_KEY: $RECAPTCHA_SITE_KEY
      RECAPTCHA_SECRET_KEY: $RECAPTCHA_SECRET_KEY
    volumes:
      - ~/.ssh:/home/rails/.ssh
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: /bin/bash

volumes:
  storage:

