version: "2"
services:
  storage:
   image: busybox
   volumes:
     - /var/lib/mysql

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: whalebirdorg
    volumes:
      - storage:/var/lib/postgres/data

  rails:
    image: ghcr.io/h3poteto/rails:3.0.0-slim-buster
    environment:
      BUNDLE_APP_CONFIG: /usr/src/app/.bundle
      SERVER_EMAIL: $SERVER_EMAIL
      SERVER_EMAIL_PASSWORD: $SERVER_EMAIL_PASSWORD
      WEB_EMAIL: $WEB_EMAIL
      SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
      RECAPTCHA_SITE_KEY: $RECAPTCHA_SITE_KEY
      RECAPTCHA_SECRET_KEY: $RECAPTCHA_SECRET_KEY
    volumes:
      - ~/.ssh:/home/rails/.ssh
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - postgres:postgres
    command: /bin/bash

volumes:
  storage:

