default: &default
  adapter: postgresql
  encoding: utf8
  pool: 2
  host: <%= ENV["DB_HOST"] || "postgres" %>
  username: <%= ENV["DB_USERNAME"] || "root" %>
  password: <%= ENV["DB_PASSWORD"] || "sample" %>
  socket: <%= ENV["DB_SOCKET"] %>

development:
  <<: *default
  database: <%= ENV["DB_WHALEBIRD_DEVELOPMENT"] || "whalebirdsocial_dev" %>

test:
  <<: *default
  database: <%= ENV["DB_WHALEBIRD_TEST"] || "whalebirdsocial_test" %>

production:
  <<: *default
  database: <%= ENV["DB_WHALEBIRD_PORDUCTION"] || "whalebirdsocial" %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV['DB_PASSWORD'] %>
